### ISSUE TITLE
个别城市无法无法生成天气实体

### ISSUE THREAD

**Issue by chenquanhao** [AgatsumaZen1tsu/homeassistant.components.weather.Weathernmc#3]
试了59659（茂名，广东下辖地级市）及其下辖县级市、区的代码，都无法生成天气实体，试了其他城市的都可以
Logger: homeassistant.components.weather
Source: custom_components/weathernmc/weather.py:122
Integration: Weather (documentation, issues)
First occurred: 14:08:42 (2 occurrences)
Last logged: 14:08:43

Error adding entities for domain weather with platform weathernmc
Error while setting up weathernmc platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 592, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/weathernmc/weather.py", line 114, in state_attributes
    data = super(NMCWeather, self).state_attributes
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 249, in state_attributes
    if self.forecast is not None:
  File "/config/custom_components/weathernmc/weather.py", line 122, in forecast
    time_str = self._forecast_data['data']['predict']['detail'][i]['date']
TypeError: string indices must be integers

**Comment by AgatsumaZen1tsu** [comment]
目前从我的抓包数据来看，中国气象台网那个API只有地级市数据，对县以及区数据不全面，官网能搜索到的城市的数据都能使用，要是官网搜索不到就没办法了

**Comment by chenquanhao** [comment]
{"station":{"code":"59659","province":"广东省","city":"茂名","url":"/publish/forecast/AGD/maoming.html"},"publish_time":"2022-03-14 18:10","weather":{"temperature":26.9,"temperatureDiff":1.1,"airpressure":9999.0,"humidity":67.0,"rain":0.0,"rcomfort":72,"icomfort":1,"info":"多云","img":"1","feelst":25.9},"wind":{"direct":"西南风","power":"微风","speed":""},"warn":{"alert":"2022年03月14日17时广东省茂名市气象台发布大雾黄色预警信号","pic":"http://www.nmc.cn/assets/img/alarm/p0005003.png","province":"广东省","city":"茂名市","url":"/publish/alarm/44090041600000_20220314170713.html","issuecontent":"茂名市气象台于03月14日17时03分发布茂名市辖区大雾黄色预警信号，请注意防御。","fmeans":"1.有关部门和单位按照职责做好防雾准备工作；2.机场、高速公路、轮渡码头等单位加强交通管理，保障安全；3.驾驶人员注意雾的变化，小心驾驶；4.户外活动注意安全。","signaltype":"大雾","signallevel":"黄色","pic2":"p0005003.png"}}
———————————————————————————————————————————————————
从插件最后那几个网址点进去来看，是能抓取到数据，就是不知为什么生成不了实体，http://www.nmc.cn/publish/forecast/AGD/maoming.html 官网也是有“茂名”的数据的
